import tokml from '@maphubs/tokml'
import shpwrite from '@mapbox/shp-write'
import { saveAs as fileSaveAs } from 'file-saver'

export function normalizeFeatures(data) {
    if (data?.type === 'FeatureCollection') {
        const { Features, ...rest } = data
        return { ...rest, features: data.features || Features || [] }
    }
    if (Array.isArray(data?.Features))
        return { type: 'FeatureCollection', features: data.Features }
    if (Array.isArray(data?.features))
        return { type: 'FeatureCollection', features: data.features }
    return { type: 'FeatureCollection', features: [] }
}

export function exportFilename(layer, fallback) {
    return layer?.display_name || fallback
}

export function exportOptions(layer, coordinateType = 'll') {
    if (!layer || !['vector', 'query'].includes(layer.type))
        return { formats: [], extents: [], coordinates: [] }
    const dynamic = layer?.variables?.dynamicExtent === true
    const hasProperties =
        layer?.variables?.getFeaturePropertiesOnClick === true &&
        layer?._lastGeodatasetRequestBody != null
    return {
        formats: [
            { value: 'geojson', label: 'GeoJSON' },
            { value: 'kml', label: 'KML' },
            { value: 'shp', label: 'SHP' },
        ],
        extents: dynamic
            ? [
                  { value: 'local', label: 'Current Extent' },
                  ...(hasProperties
                      ? [
                            {
                                value: 'raw-extent',
                                label: 'Current Extent w/ Props',
                            },
                        ]
                      : []),
                  { value: 'raw', label: 'Entire File' },
              ]
            : [{ value: 'local', label: 'Current Extent' }],
        coordinates:
            coordinateType !== 'll'
                ? [
                      { value: 'source', label: 'Source Coordinates' },
                      {
                          value: coordinateType,
                          label: `Converted (${coordinateType})`,
                      },
                  ]
                : [{ value: 'source', label: 'Source Coordinates' }],
    }
}

function copyRequestBody(layer) {
    const body = JSON.parse(JSON.stringify(layer?._lastGeodatasetRequestBody))
    delete body._source
    delete body.noDuplicates
    return body
}

function requestApi(api, endpoint, params) {
    return new Promise((resolve, reject) => {
        api.api(endpoint, params, resolve, reject)
    })
}

function requestJson(url) {
    return fetch(url).then((response) => {
        if (!response.ok) throw new Error(`HTTP ${response.status}`)
        return response.json()
    })
}

export function createExportAdapter({
    layers,
    api,
    convert,
    formulae,
    fetchKml,
    isKml,
    coordinateType = 'll',
    customCRS,
    saveAs,
    toast,
}) {
    const getLayer = (name) => {
        const uuid = layers.asLayerUUID?.(name) || name
        return layers.layers?.data?.[uuid] || layers.layers?.data?.[name]
    }
    const downloadObject =
        formulae?.downloadObject ||
        ((value, filename, extension) => {
            const blob = new Blob([JSON.stringify(value)], {
                type: extension === '.kml' ? 'application/xml' : 'application/json',
            })
            ;(saveAs || fileSaveAs)(blob, `${filename}${extension}`)
        })

    const downloadGeoJson = (geojson, filename, format, layer) => {
        if (format === 'geojson') {
            downloadObject(geojson, filename, '.geojson')
            return
        }
        if (format === 'kml') {
            const kml = tokml(
                formulae.geoJSONForceSimpleStyleSpec(
                    geojson,
                    true,
                    layer?.style,
                    layer?.useKeyAsName
                ),
                {
                    name: layer?.useKeyAsName || false,
                    description: 'Generated by MMGIS',
                    timestamp:
                        layer?.time?.enabled === true
                            ? layer.time.endProp || null
                            : null,
                    simplestyle: true,
                }
            )
            downloadObject(kml, filename, '.kml', 'xml')
            return
        }
        return requestApi(api, 'proj42wkt', {
            proj4: customCRS?.projString,
        })
            .then((projection) =>
                shpwrite
                    .zip(geojson, {
                        outputType: 'blob',
                        prj: projection,
                    })
                    .then((content) =>
                        (saveAs || fileSaveAs)(content, `${filename}.zip`)
                    )
            )
            .catch((error) => {
                toast?.warning?.(
                    `Failed to generate shapefile's .prj.`,
                    6000
                )
                error.toastHandled = true
                throw error
            })
    }

    return {
        isLayerOn: (name) => {
            const uuid = layers.asLayerUUID?.(name) || name
            const runtime = layers.layers?.layer?.[uuid]
            return runtime != null && layers.layers?.on?.[uuid] === true
        },
        getLayerData: getLayer,
        getOptions: (name) => exportOptions(getLayer(name), coordinateType),
        canExport: (name) =>
            ['vector', 'query'].includes(getLayer(name)?.type),
        getApi: () => api,
        fetchGeodataset: (params) => api.api('geodatasets_get', params),
        normalizeFeatures,
        convertCoordinates: (geojson) => convert(geojson),
        notify: (kind, message, duration = 6000) =>
            toast?.[kind]?.(message, duration),
        async exportLayer(name, options = {}) {
            const layer = getLayer(name)
            if (!layer || !this.canExport(name))
                throw new Error('Layer cannot be exported.')
            if (!this.isLayerOn(name)) {
                const error = new Error(
                    'Please turn layer on before exporting.'
                )
                toast?.warning?.(
                    'Please turn layer on before exporting.',
                    6000
                )
                error.toastHandled = true
                throw error
            }

            const format = options.format || 'geojson'
            const extent = options.extent || 'local'
            const coords = options.coords || 'source'
            let geojson
            if (extent === 'local') {
                const runtime =
                    layers.layers.layer[layer.name || name] ||
                    layers.layers.layer[name]
                if (!runtime?.toGeoJSON)
                    throw new Error('Layer data is unavailable.')
                geojson = runtime.toGeoJSON(
                    layers.GEOJSON_PRECISION
                )
            } else if (extent === 'raw-extent') {
                geojson = await requestApi(
                    api,
                    'geodatasets_get',
                    copyRequestBody(layer)
                )
            } else {
                if (
                    String(layer.url || '')
                        .toLowerCase()
                        .startsWith('geodatasets:')
                ) {
                    const [, dataset] = String(layer.url).split(':')
                    const response = await requestApi(api, 'geodatasets_get', {
                        layer: dataset,
                        type: 'geojson',
                    })
                    geojson = response.body
                } else {
                    const url = layers.getUrl(layer.type, layer.url, layer)
                    if (isKml?.(url)) {
                        geojson = await new Promise((resolve, reject) =>
                            fetchKml(url, resolve, (_request, _status, error) =>
                                reject(
                                    error || new Error('Failed to parse KML.')
                                )
                            )
                        )
                    } else {
                        geojson = await requestJson(url)
                    }
                }
            }
            geojson = normalizeFeatures(geojson)
            if (coords !== 'source') geojson = convert(geojson)
            const filename = exportFilename(layer, name)
            await downloadGeoJson(geojson, filename, format, layer)
            return { filename, format, geojson }
        },
    }
}
